export const CALENDAR_CHANGE_MONTH = '[CALENDAR] CALENDAR_CHANGE_MONTH';
export const CALENDAR_ADD_REMINDER = '[CALENDAR] CALENDAR_ADD_REMINDER';
export const CALENDAR_SELECTED_REMINDER = '[CALENDAR] CALENDAR_SELECTED_REMINDER';
export const CALENDAR_UPDATE_REMINDER = '[CALENDAR] CALENDAR_UPDATE_REMINDER';
export const CALENDAR_DELETE_REMINDERS_BY_ID = '[CALENDAR] CALENDAR_DELETE_REMINDERS_BY_ID';
